global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Add any alerting rules here

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'genkit-direct'
    static_configs:
      - targets: ['host.docker.internal:4033']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s
